"""No instruction says `scripts/build_page_board.py` makes `data/page-map.json`.

The page map is the WordPress extractor's record of the OLD site: `scripts/extract_writers.py`
writes it (`npm run extract`) and nothing regenerates it. `scripts/build_page_board.py` only
READS it (for routes) and renders one board record, `data/boards/<slug>.json`, as its board
Artifact. The project-5 readiness review (2026-09-24) found WORKFLOW.md and two architect agents
telling a builder to "run build_page_board" to get a page-map entry — for a new page (a
comparison page, a hub, a blog post) that sends the builder after a row that can never exist.
A new page's record is its board, written first (CLAUDE.md's board flow), plus `dist/` once built.

A line that names both files is a claim about how they relate; the only true one is that the
board builder reads the map.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]

SCANNED = sorted(
    [ROOT / "CLAUDE.md", ROOT / "README.md"]
    + list((ROOT / "docs/reference").glob("*.md"))
    + list((ROOT / "rules").glob("*.md"))
    + list((ROOT / ".claude/agents").glob("*.md"))
    + list((ROOT / ".claude/skills").glob("*/SKILL.md"))
    + list((ROOT / ".claude/commands").glob("*.md"))
)

BOTH = re.compile(r"page-map.*build_page_board|build_page_board.*page-map")
# The board builder as the subject of "reads", or the map explicitly NOT made by it. A bare
# "read it" elsewhere on the line ("generated by build_page_board — read it first") is no excuse.
TRUE_RELATION = re.compile(r"build_page_board(?:\.py)?`?\s+(?:only\s+)?reads\b"
                           r"|\b(?:not|never) (?:generated|regenerated|written)\b", re.I)


def offenders(text):
    """1-based numbers of the lines that tie the page map to the board builder as its maker."""
    return [n for n, line in enumerate(text.splitlines(), 1)
            if BOTH.search(line) and not TRUE_RELATION.search(line)]


def test_scanned_trees_are_present():
    assert any(p.name == "WORKFLOW.md" for p in SCANNED)
    assert sum(1 for p in SCANNED if p.parent.name == "agents") >= 40


def test_no_line_says_build_page_board_makes_the_page_map():
    hits = []
    for p in SCANNED:
        lines = p.read_text(encoding="utf-8").splitlines()
        hits += [f"{p.relative_to(ROOT)}:{n}: {lines[n - 1].strip()[:160]}"
                 for n in offenders("\n".join(lines))]
    assert not hits, (
        "data/page-map.json is written only by scripts/extract_writers.py (npm run extract) and "
        "is never regenerated; build_page_board.py only reads it. A new page's record is its "
        "board, data/boards/<slug>.json:\n" + "\n".join(hits))


def test_the_guard_fires_on_the_false_claims_and_spares_the_true_one():
    bad = [
        "| Page map | `data/page-map.json` | Run `python3 scripts/build_page_board.py` |",
        "- Page Map Entry: [yes — the slug is in data/page-map.json | no → run python3 scripts/build_page_board.py first]",
        "`data/page-map.json` is generated by `scripts/build_page_board.py`; never hand-edit it.",
        "`python3 scripts/build_page_board.py` regenerates `data/page-map.json` and the boards",
        "| `data/page-map.json` | `scripts/build_page_board.py` | content-architect | Every build |",
        "6. **`data/page-map.json`** is the page inventory (generated by `scripts/build_page_board.py`) — read it first",
    ]
    for line in bad:
        assert offenders(line) == [1], line
    good = [
        "`scripts/build_page_board.py` reads `data/page-map.json` for the routes it resolves.",
        "`data/page-map.json` is not generated by `scripts/build_page_board.py`.",
        "`python3 scripts/build_page_board.py <slug>` renders the board record.",
        "`data/page-map.json` is the extractor's record of the old site.",
    ]
    for line in good:
        assert offenders(line) == [], line
