"""Four SVG lockups, four favicon renders, header/footer on the SVG logo, no raster logo left.

Task 20. The lockups are generated by scripts/build_lockups.py from the ONE copy of the
mark's geometry (src/components/kit/markShapes.ts) and the ONE place a colour is spelled
(src/styles/tokens.css); these assertions are the contract that generator has to keep, so
that a hand-edit or a drifted regeneration is caught rather than shipped.

public/brand/*.svg are the only files outside tokens.css allowed to spell a brand hex: they
are standalone SVG documents with no stylesheet to resolve a custom property against.
test_design_tokens.py::test_no_hex_anywhere_in_src_except_tokens scans src/ only.
"""
import json
import pathlib
import re
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[2]
BRAND = ROOT / "public/brand"
LOCKUPS = ["logo-horizontal.svg", "logo-stacked.svg", "logo-icon.svg", "logo-mono.svg"]
FAVS = ["favicon.svg", "favicon-32.png", "apple-touch-icon.png", "icon-512.png"]


def test_lockups_exist_parse_and_carry_a_title():
    for f in LOCKUPS:
        p = BRAND / f
        assert p.exists(), f
        root = ET.fromstring(p.read_bytes())
        assert root.tag.endswith("svg")
        assert root.get("role") == "img", f
        assert any(el.tag.endswith("title") for el in root.iter()), f
        assert not any(el.tag.endswith("text") for el in root.iter()), f"{f} must outline its text"
        assert not any(el.tag.endswith("image") for el in root.iter()), f


def test_lockups_carry_the_badge_geometry():
    """Every lockup is the L1 badge, not a redraw of it: the roundel at r=47 and the brass
    ring at r=43 are markShapes.ts's own two circles, and a lockup that lost them has been
    hand-edited away from the mark the site renders."""
    for f in LOCKUPS:
        svg = (BRAND / f).read_text(encoding="utf-8")
        radii = set(re.findall(r'<circle[^>]*\br="([\d.]+)"', svg))
        assert {"47", "43"} <= radii, f"{f}: badge circles r=47 and r=43, got {radii}"


def test_mono_uses_currentcolor_only():
    t = (BRAND / "logo-mono.svg").read_text()
    assert "currentColor" in t and not re.search(r"#[0-9a-fA-F]{3,6}", t)
    # Three tones, not one flat silhouette: the ink at full, the ears and the skull below it.
    assert {"1", "0.55", "0.25"} <= set(re.findall(r'-opacity="([\d.]+)"', t))


def test_colour_lockups_spell_only_token_hexes():
    """A hex in public/brand/ is allowed, but only one tokens.css resolves to — the
    generator substitutes them, so a stray shade means someone typed a colour by hand."""
    tokens = (ROOT / "src/styles/tokens.css").read_text(encoding="utf-8")
    allowed = {h.upper() for h in re.findall(r"#[0-9A-Fa-f]{3,8}", tokens)}
    for f in ("logo-horizontal.svg", "logo-stacked.svg", "logo-icon.svg"):
        used = {h.upper() for h in re.findall(r"#[0-9A-Fa-f]{3,8}", (BRAND / f).read_text())}
        assert used and used <= allowed, f"{f}: {sorted(used - allowed)} are not tokens"


def test_favicons_exist():
    for f in FAVS:
        assert (ROOT / "public" / f).exists(), f


def test_settings_and_shell_use_the_svg_logo():
    s = json.loads((ROOT / "data/settings.json").read_text())
    assert s["logo"] == "/brand/logo-stacked.svg" and s["logo_header"] == "/brand/logo-horizontal.svg"
    for f in ("SiteHeader.astro", "SiteFooter.astro"):
        assert "logo" in (ROOT / "src/components" / f).read_text().lower()
    src = "\n".join(p.read_text() for p in (ROOT / "src").rglob("*.astro"))
    assert "blue-staffy-uk-official-logo0.png" not in src and "header-logo-88.webp" not in src
    # Deliberately NOT asserted absent. Working rule 11 (CLAUDE.md) requires every
    # already-served image URL to keep resolving, so the two legacy logo rasters stay in
    # public/images/ even though no component references them any more. Their continued
    # presence is asserted in tests/py/test_images.py; this test owns only the reference side.


def test_structured_data_and_og_point_at_the_raster():
    """Neither Google's structured-data pipeline nor a social card renderer takes an SVG,
    so `image`/`og:image` keep a PNG even though the visible logo is now vector."""
    site = (ROOT / "src/lib/site.ts").read_text(encoding="utf-8")
    assert "'/icon-512.png'" in site, "site.ts should export the raster logo path"
    for f in ("src/components/Schema.astro", "src/layouts/BaseLayout.astro"):
        assert "SITE.logo" not in (ROOT / f).read_text(encoding="utf-8"), \
            f"{f} must use the raster export, not the SVG in settings.logo"
