#!/usr/bin/env bash
# =============================================================================
# BSUK FULL SYSTEM HEALTH SWEEP
# One command that checks everything: git/deploy state, agent integrity,
# Astro build, live site, and built-output hygiene.
#
# Usage:   bash scripts/health-sweep.sh           # full sweep (runs build)
#          bash scripts/health-sweep.sh --no-build # skip the build step (faster)
#
# Exit code 0 = all critical checks passed, 1 = at least one critical failure.
# Designed for BlueStaffyUK (Astro -> static dist/; no host until project 6).
# =============================================================================
# -e is deliberately NOT set: a sweep whose job is to report every failure must keep going
# past the first one. Each check records its own verdict in $FAIL, and the RESULT block is
# what decides the exit code.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

BUILD_LOG=$(mktemp -t bsuk-build)
trap 'rm -f "$BUILD_LOG"' EXIT

DOMAIN="${SITE_URL:-}"
RUN_BUILD=1
[ "${1:-}" = "--no-build" ] && RUN_BUILD=0

FAIL=0
pass()  { printf "  \033[32mPASS\033[0m  %s\n" "$1"; }
warn()  { printf "  \033[33mWARN\033[0m  %s\n" "$1"; }
fail()  { printf "  \033[31mFAIL\033[0m  %s\n" "$1"; FAIL=1; }
hdr()   { printf "\n\033[1m== %s ==\033[0m\n" "$1"; }

echo "BSUK HEALTH SWEEP — $(date '+%Y-%m-%d %H:%M:%S')"

# -----------------------------------------------------------------------------
hdr "1. GIT / DEPLOY STATE"
# -----------------------------------------------------------------------------
BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "  branch: $BRANCH"

# Secret leak: token embedded in remote URL is a credential exposure.
if git remote -v | grep -qE 'ghp_|github_pat_|x-access-token:[^@]+@'; then
  fail "GitHub token embedded in remote URL (.git/config) — rotate + use a credential helper"
else
  pass "No token embedded in remote URL"
fi
# Secret leak: a Cloudflare/API token committed inside tracked Claude settings or scripts.
if git grep -qE 'CLOUDFLARE_API_TOKEN=[A-Za-z0-9_-]{20,}|cfut_[A-Za-z0-9_-]{20,}' -- ':!*.md' ':!scripts/health-sweep.sh' 2>/dev/null; then
  fail "API token committed in tracked files (git grep CLOUDFLARE_API_TOKEN= / cfut_) — rotate + purge"
else
  pass "No API token committed in tracked files"
fi
if git ls-files --error-unmatch .claude/settings.local.json >/dev/null 2>&1; then
  fail ".claude/settings.local.json is tracked — it is per-machine and must stay gitignored"
else
  pass ".claude/settings.local.json is not tracked"
fi

git fetch -q origin "$BRANCH" 2>/dev/null
AHEAD=$(git rev-list --count origin/"$BRANCH"..HEAD 2>/dev/null || echo "?")
BEHIND=$(git rev-list --count HEAD..origin/"$BRANCH" 2>/dev/null || echo "?")
if [ "$AHEAD" = "0" ]; then pass "Up to date with origin (0 unpushed commits)"
else warn "$AHEAD commit(s) committed but NOT pushed/deployed"; fi
[ "$BEHIND" != "0" ] && [ "$BEHIND" != "?" ] && warn "$BEHIND commit(s) on origin not pulled"

DIRTY=$(git status --short | wc -l | tr -d ' ')
if [ "$DIRTY" = "0" ]; then pass "Working tree clean"
else warn "$DIRTY uncommitted file(s) (not deployed) — run: git status --short"; fi

# -----------------------------------------------------------------------------
hdr "2. AGENT SYSTEM INTEGRITY"
# -----------------------------------------------------------------------------
ACOUNT=$(ls .claude/agents/*.md 2>/dev/null | wc -l | tr -d ' ')
echo "  agents found: $ACOUNT"
amiss=0
# An unmatched glob expands to the literal pattern, which read as three FAILs for a file
# named `*.md`. No agents yet (they arrive in Task 12) is a WARN, not a frontmatter defect.
if [ "$ACOUNT" = "0" ]; then
  warn "no .claude/agents/*.md yet — the curated agents arrive in Task 12"
fi
for f in .claude/agents/*.md; do
  [ -e "$f" ] || continue
  head -8 "$f" | grep -q "^name:"        || { fail "missing name: $(basename "$f")"; amiss=1; }
  head -8 "$f" | grep -q "^description:" || { fail "missing description: $(basename "$f")"; amiss=1; }
  head -8 "$f" | grep -qE "^model: *(inherit|[a-z0-9-]+)" || { fail "missing model: $(basename "$f")"; amiss=1; }
done
[ $amiss -eq 0 ] && pass "All $ACOUNT agents have name + description + model frontmatter"

# scripts/verify_model_tiers.sh is not ported (spec §1). The registry it verified is
# regenerated by scripts/build_agent_registry.py, which Task 11 supplies; until then this
# check is silently absent rather than silently passing.
if [ -f scripts/build_agent_registry.py ]; then
  if python3 scripts/build_agent_registry.py --check; then pass "Agent registry in sync"
  else fail "Agent registry drift — run: python3 scripts/build_agent_registry.py"; fi
else
  warn "scripts/build_agent_registry.py absent — agent-registry check arrives in Task 11"
fi

# The system registry is derived the same way, and drifts the same way: the source repo's
# was hand-maintained until it claimed 68 agents over 67 files.
if [ -f scripts/build_system_registry.py ]; then
  if python3 scripts/build_system_registry.py --check; then pass "System registry in sync"
  else fail "System registry drift — run: python3 scripts/build_system_registry.py"; fi
else
  warn "scripts/build_system_registry.py absent"
fi
echo "  skills found: $(ls -d .claude/skills/*/SKILL.md 2>/dev/null | wc -l | tr -d ' ')"

# register_skills.py is not ported: spec §1 retires the flat skills/*.md mirror, so a check
# that the mirror is in sync is a check for a thing that no longer exists. The zero-tolerance
# marker gate is what has to hold instead.
python3 scripts/marker_check.py || FAIL=1

# The render baseline table in docs/reports/ is derived from the scorecards and from each
# check's `severity:` in tests/render/checks/*.ts. Hand-editing either side silently rots the
# number the Task 20 gate report quotes, so the sweep regenerates it and compares.
if [ -f scripts/render_baseline.py ] && ls data/quality/scorecards/*.json >/dev/null 2>&1; then
  # The LIVE baseline is project 3's. Project 2's file is the published record of a finished
  # run and is deliberately never regenerated or checked here.
  BASELINE_REPORT=docs/reports/render-baseline-project3.md
  if python3 scripts/render_baseline.py --check --out "$BASELINE_REPORT"; then pass "Render baseline report in sync"
  else fail "Render baseline drift — run: python3 scripts/render_baseline.py --out $BASELINE_REPORT"; fi
else
  warn "no scorecards yet — render-baseline check skipped (run node scripts/build_scorecard.mjs)"
fi

# -----------------------------------------------------------------------------
hdr "3. ASTRO BUILD"
# -----------------------------------------------------------------------------
if [ $RUN_BUILD -eq 1 ]; then
  if npm run build > "$BUILD_LOG" 2>&1; then
    PAGES=$(grep -oE '[0-9]+ page\(s\) built' "$BUILD_LOG" | tail -1)
    pass "Build succeeded — ${PAGES:-completed}"
  else
    fail "Build FAILED — last 15 lines below (the full log is a temp file, removed on exit)"
    tail -15 "$BUILD_LOG" | sed 's/^/      /'
  fi
else
  warn "Build skipped (--no-build)"
fi

# -----------------------------------------------------------------------------
hdr "4. LIVE SITE"
# -----------------------------------------------------------------------------
if [ -n "$DOMAIN" ]; then
  for path in "/" "/buy-blue-staffy-puppies-uk/" "/available-puppies/"; do
    CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "$DOMAIN$path")
    if [ "$CODE" = "200" ]; then pass "$path -> 200"
    else fail "$path -> $CODE"; fi
  done
  WWW=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "${DOMAIN/https:\/\//https:\/\/www.}/")
  if [ "$WWW" = "301" ] || [ "$WWW" = "308" ]; then pass "www -> $WWW (redirect)"
  else warn "www -> $WWW (expected 301/308)"; fi
else
  warn "no SITE_URL — skipping live checks (project 6)"
fi

# -----------------------------------------------------------------------------
hdr "5. BUILT-OUTPUT HYGIENE (dist/)"
# -----------------------------------------------------------------------------
if [ -d dist ]; then
  python3 - <<'PY'
import re, glob, sys
DIST="dist"; broken=0; rel=0; nocanon=0; pages=0
for f in glob.glob(f"{DIST}/**/index.html", recursive=True):
    pages+=1
    c=open(f, encoding='utf-8', errors='ignore').read()
    broken+=len(re.findall(r'src="data:image/gif;base64,', c))
    cs=re.findall(r'<link[^>]*rel=["\']canonical["\'][^>]*href="([^"]*)"', c)
    if not cs: nocanon+=1
    rel+=sum(1 for x in cs if not x.startswith('http'))
def line(ok,msg):
    print(("  \033[32mPASS\033[0m  " if ok else "  \033[31mFAIL\033[0m  ")+msg)
line(True, f"{pages} built pages scanned")
line(broken==0, f"broken lazy-load GIF images: {broken}")
line(nocanon==0, f"pages missing canonical: {nocanon}")
line(rel==0, f"relative canonicals: {rel}")
sys.exit(1 if (broken or nocanon or rel) else 0)
PY
  [ $? -ne 0 ] && FAIL=1
else
  warn "dist/ not present — run a build first for output hygiene checks"
fi

# -----------------------------------------------------------------------------
hdr "RESULT"
# -----------------------------------------------------------------------------
if [ $FAIL -eq 0 ]; then
  printf "\033[32mALL CRITICAL CHECKS PASSED\033[0m\n"; exit 0
else
  printf "\033[31mONE OR MORE CRITICAL CHECKS FAILED — see above\033[0m\n"; exit 1
fi
